# Generated by Django 4.2 on 2023-04-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_duration_alter_movie_synopsis_movieorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
